
import React from 'react';
import { Page, WaterSourceStatus, HealthCenterType, type WaterSource, type Alert, type HealthCenter, type Symptom, type SymptomReport } from './types';
import { HomeIcon, MapIcon, AlertIcon, BookOpenIcon, HeartIcon, UsersIcon } from './components/icons';

export const APP_NAME = "Aqua Guardian";

export const NAVIGATION_ITEMS = [
  { page: Page.Home, icon: <HomeIcon />, labelKey: 'home' },
  { page: Page.Map, icon: <MapIcon />, labelKey: 'map' },
  { page: Page.Alerts, icon: <AlertIcon />, labelKey: 'alerts' },
  { page: Page.Education, icon: <BookOpenIcon />, labelKey: 'education' },
  { page: Page.Health, icon: <HeartIcon />, labelKey: 'health' },
  { page: Page.Community, icon: <UsersIcon />, labelKey: 'community' },
];

export const LANGUAGES = {
  en: 'English',
  hi: 'हिन्दी',
  as: 'অসমীয়া',
};

export const TRANSLATIONS: { [key: string]: { [key: string]: string } } = {
  en: {
    home: 'Home',
    map: 'Map',
    alerts: 'Alerts',
    education: 'Education',
    health: 'Health',
    community: 'Community',
    water_status: 'Water Status',
    primary_source: 'Primary Water Source',
    last_checked: 'Last Checked',
    status_safe: 'Safe',
    status_warning: 'Warning',
    status_unsafe: 'Unsafe',
    view_map: 'View Map',
    recent_alerts: 'Recent Alerts',
    health_companion: 'Health Companion',
    symptom_checker: 'Symptom Checker',
    find_care: 'Find Nearest Care',
    community_hub: 'Community Hub',
    report_symptoms: 'Report Symptoms',
    view_dashboard: 'View Dashboard',
    alert_history: 'Alert History',
    all_alerts_for_area: 'All past alerts for your area are logged here.',
    boil_water_title: 'How to Boil Water Safely',
    boil_water_desc: 'Boiling is the surest method to kill disease-causing organisms, including viruses, bacteria, and parasites.',
    symptoms_title: 'Common Water-Borne Diseases',
    cholera: 'Cholera',
    typhoid: 'Typhoid',
    diarrhea: 'Diarrhea',
    hygiene_title: 'Hygiene Best Practices',
    hygiene_desc: 'Safe water handling, sanitation, and handwashing are crucial for preventing illness.',
    health_support: 'Integrated Healthcare Support',
    symptom_checker_prompt: 'Input your symptoms to get a basic assessment and recommended actions.',
    select_symptoms: 'Select your symptoms',
    check_symptoms: 'Check Symptoms',
    disclaimer: 'Disclaimer: This is not a medical diagnosis. Consult a healthcare professional for accurate advice.',
    home_remedies: 'Home Remedies Library',
    ors_title: 'How to Prepare ORS',
    find_nearest_care: 'Find Nearest Care',
    community_reporting: 'Community Reporting',
    crowdsourced_reporting: 'Crowdsourced Symptom Reporting',
    report_symptoms_desc: 'Anonymously report symptoms to help health officials detect outbreaks early.',
    submit_report: 'Submit Report',
    resource_dashboard: 'Resource Dashboard',
    community_health_data: 'Community health data visualization.',
    reports_by_symptom: 'Reports by Symptom',
    symptom_trend: 'Symptom Trend (Last 7 Days)',
    total_reports: 'Total Reports',
    send_feedback: 'Send Feedback',
    feedback_title: 'Share Your Feedback',
    feedback_prompt: "We'd love to hear from you! Please share any bugs or suggestions.",
    feedback_placeholder: "Type your feedback here...",
    submit: "Submit",
    cancel: "Cancel",
    feedback_thanks: "Thank you for your feedback!",
    sending: "Sending...",
  },
  hi: {
    home: 'होम',
    map: 'नक्शा',
    alerts: 'अलर्ट',
    education: 'शिक्षा',
    health: 'स्वास्थ्य',
    community: 'समुदाय',
    water_status: 'पानी की स्थिति',
    primary_source: 'प्राथमिक जल स्रोत',
    last_checked: 'पिछલી बार जांचा गया',
    status_safe: 'सुरक्षित',
    status_warning: 'चेतावनी',
    status_unsafe: 'असुरक्षित',
    view_map: 'नक्शा देखें',
    recent_alerts: 'हाल के अलर्ट',
    health_companion: 'स्वास्थ्य साथी',
    symptom_checker: 'लक्षण परीक्षक',
    find_care: 'निकटतम देखभाल खोजें',
    community_hub: 'सामुदायिक हब',
    report_symptoms: 'लक्षणों की रिपोर्ट करें',
    view_dashboard: 'डैशबोर्ड देखें',
    alert_history: 'अलर्ट इतिहास',
    all_alerts_for_area: 'आपके क्षेत्र के सभी पिछले अलर्ट यहां लॉग किए गए हैं।',
    boil_water_title: 'पानी को सुरक्षित रूप से कैसे उबालें',
    boil_water_desc: 'उबालना वायरस, बैक्टीरिया और परजीवी सहित रोग पैदा करने वाले जीवों को मारने का सबसे निश्चित तरीका है।',
    symptoms_title: 'आम जल जनित रोग',
    cholera: 'हैजा',
    typhoid: 'टाइफाइड',
    diarrhea: 'दस्त',
    hygiene_title: 'स्वच्छता सर्वोत्तम अभ्यास',
    hygiene_desc: 'बीमारी को रोकने के लिए सुरक्षित जल प्रबंधन, स्वच्छता और हाथ धोना महत्वपूर्ण है।',
    health_support: 'एकीकृत स्वास्थ्य सहायता',
    symptom_checker_prompt: 'बुनियादी मूल्यांकन और अनुशंसित कार्रवाइयां प्राप्त करने के लिए अपने लक्षण इनपुट करें।',
    select_symptoms: 'अपने लक्षण चुनें',
    check_symptoms: 'लक्षणों की जाँच करें',
    disclaimer: 'अस्वीकरण: यह एक चिकित्सा निदान नहीं है। सटीक सलाह के लिए किसी स्वास्थ्य पेशेवर से सलाह लें।',
    home_remedies: 'घरेलू उपचार पुस्तकालय',
    ors_title: 'ओआरएस कैसे तैयार करें',
    find_nearest_care: 'निकटतम देखभाल खोजें',
    community_reporting: 'सामुदायिक रिपोर्टिंग',
    crowdsourced_reporting: 'क्राउडसोर्स्ड लक्षण रिपोर्टिंग',
    report_symptoms_desc: 'स्वास्थ्य अधिकारियों को प्रकोप का शीघ्र पता लगाने में मदद करने के लिए गुमनाम रूप से लक्षणों की रिपोर्ट करें।',
    submit_report: 'रिपोर्ट सबमिट करें',
    resource_dashboard: 'संसाधन डैशबोर्ड',
    community_health_data: 'सामुदायिक स्वास्थ्य डेटा विज़ुअलाइज़ेशन।',
    reports_by_symptom: 'लक्षण के अनुसार रिपोर्ट',
    symptom_trend: 'लक्षण प्रवृत्ति (पिछले 7 दिन)',
    total_reports: 'कुल रिपोर्ट',
    send_feedback: 'प्रतिक्रिया भेजें',
    feedback_title: 'अपनी प्रतिक्रिया साझा करें',
    feedback_prompt: 'हमें आपसे सुनना अच्छा लगेगा! कृपया कोई भी बग या सुझाव साझा करें।',
    feedback_placeholder: "अपनी प्रतिक्रिया यहां टाइप करें...",
    submit: "सबमिट करें",
    cancel: "रद्द करें",
    feedback_thanks: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    sending: "भेजा जा रहा है...",
  },
  as: {
    home: 'গৃহ',
    map: 'মানচিত্ৰ',
    alerts: 'সতৰ্কবাণী',
    education: 'শিক্ষা',
    health: 'স্বাস্থ্য',
    community: 'সম্প্ৰদায়',
    water_status: 'পানীৰ স্থিতি',
    primary_source: 'প্ৰাথমিক পানীৰ উৎস',
    last_checked: 'শেষ পৰীক্ষা কৰা হৈছে',
    status_safe: 'সুৰক্ষিত',
    status_warning: 'সাৱধান',
    status_unsafe: 'অসুৰক্ষিত',
    view_map: 'মানচিত্ৰ চাওক',
    recent_alerts: 'শেহতীয়া সতৰ্কবাণী',
    health_companion: 'স্বাস্থ্য সঙ্গী',
    symptom_checker: 'ৰোগৰ লক্ষণ পৰীক্ষক',
    find_care: 'নিকটতম যত্ন বিচাৰক',
    community_hub: 'সম্প্ৰদায় কেন্দ্ৰ',
    report_symptoms: 'ৰোগৰ লক্ষণ জনোৱা',
    view_dashboard: 'ডেশ্ববৰ্ড চাওক',
    alert_history: 'সতৰ্কবাণীৰ ইতিহাস',
    all_alerts_for_area: 'আপোনাৰ অঞ্চলৰ সকলো পুৰণি সতৰ্কবাণী ইয়াত লিপিবদ্ধ কৰা হৈছে।',
    boil_water_title: 'কিভাবে সুৰক্ষিতভাৱে পানী উতলাব',
    boil_water_desc: 'ভাইৰাছ, বেক্টেৰিয়া আৰু পৰজীৱীকে ধৰি ৰোগ সৃষ্টিকাৰী জীৱাণুবোৰক মাৰিবলৈ উতলোৱা হৈছে আটাইতকৈ নিশ্চিত পদ্ধতি।',
    symptoms_title: 'সাধাৰণ পানীজনিত ৰোগ',
    cholera: 'কলেরা',
    typhoid: 'টাইফয়েড',
    diarrhea: 'ডায়েৰিয়া',
    hygiene_title: 'স্বাস্থ্যবিধিৰ শ্ৰেষ্ঠ পদ্ধতি',
    hygiene_desc: 'ৰোগ প্ৰতিৰোধৰ বাবে সুৰক্ষিত পানী ব্যৱহাৰ, অনাময় আৰু হাত ধোৱা অতি গুৰুত্বপূৰ্ণ।',
    health_support: 'সংহত স্বাস্থ্যসেৱা সমৰ্থন',
    symptom_checker_prompt: 'এটা সাধাৰণ মূল্যায়ন আৰু পৰামৰ্শিত কাৰ্য্যকলাপ পাবলৈ আপোনাৰ লক্ষণবোৰ ইনপুট কৰক।',
    select_symptoms: 'আপোনাৰ লক্ষণবোৰ বাছনি কৰক',
    check_symptoms: 'লক্ষণবোৰ পৰীক্ষা কৰক',
    disclaimer: 'অস্বীকাৰ: এইটো এটা চিকিৎসা নিদান নহয়। সঠিক পৰামৰ্শৰ বাবে স্বাস্থ্যসেৱা পেছাদাৰীৰ লগত পৰামৰ্শ কৰক।',
    home_remedies: 'ঘৰুৱা প্ৰতিকাৰ পুথিভঁৰাল',
    ors_title: 'কিভাবে ORS প্ৰস্তুত কৰিব',
    find_nearest_care: 'নিকটতম যত্ন বিচাৰক',
    community_reporting: 'সম্প্ৰদায়ৰ প্ৰতিবেদন',
    crowdsourced_reporting: 'ক্ৰাউডচৰ্চড লক্ষণ প্ৰতিবেদন',
    report_symptoms_desc: 'স্বাস্থ্য বিষয়াসকলক সোনকালে ৰোগৰ প্ৰাদুৰ্ভাৱ ধৰা পেলোৱাত সহায় কৰিবলৈ বেনামীভাৱে লক্ষণবোৰৰ বিষয়ে জনাওক।',
    submit_report: 'প্ৰতিবেদন দাখিল কৰক',
    resource_dashboard: 'সম্পদ ডেশ্ববৰ্ড',
    community_health_data: 'সম্প্ৰদায়ৰ স্বাস্থ্য তথ্যৰ দৃশ্যমান উপস্থাপন।',
    reports_by_symptom: 'লক্ষণ অনুসৰি প্ৰতিবেদন',
    symptom_trend: 'লক্ষণৰ প্ৰවণতা (শেষ ৭ দিন)',
    total_reports: 'মুঠ প্ৰতিবেদন',
    send_feedback: 'মতামত পঠিয়াওক',
    feedback_title: 'আপোনাৰ মতামত জনাওক',
    feedback_prompt: "আমি আপোনাৰ পৰা শুনি ভাল পাম! অনুগ্ৰহ কৰি যিকোনো আসোঁৱাহ বা পৰামৰ্শ জনাওক।",
    feedback_placeholder: "আপোনাৰ মতামত ইয়াত টাইপ কৰক...",
    submit: "দাখিল কৰক",
    cancel: "বাতিল কৰক",
    feedback_thanks: "আপোনাৰ মতামতৰ বাবে ধন্যবাদ!",
    sending: "পঠিওৱা হৈছে...",
  }
};

// Mock Data
export const WATER_SOURCES: WaterSource[] = [
    { id: 1, name: 'Village Well #1', lat: 26.1445, lng: 91.7362, status: WaterSourceStatus.Safe, lastChecked: '2024-07-29 08:00 AM' },
    { id: 2, name: 'River Pump Station', lat: 26.1550, lng: 91.7490, status: WaterSourceStatus.Warning, lastChecked: '2024-07-29 09:30 AM' },
    { id: 3, name: 'Community Hand Pump', lat: 26.1390, lng: 91.7280, status: WaterSourceStatus.Unsafe, lastChecked: '2024-07-29 07:45 AM' },
    { id: 4, name: 'School Water Tank', lat: 26.1485, lng: 91.7395, status: WaterSourceStatus.Safe, lastChecked: '2024-07-28 05:00 PM' },
];

export const ALERTS: Alert[] = [
    { id: 1, sourceName: 'Community Hand Pump', message: 'High levels of E. coli detected. Do not drink.', status: WaterSourceStatus.Unsafe, timestamp: '2024-07-29 07:45 AM' },
    { id: 2, sourceName: 'River Pump Station', message: 'Increased turbidity detected after heavy rainfall. Advised to boil before use.', status: WaterSourceStatus.Warning, timestamp: '2024-07-29 09:30 AM' },
    { id: 3, sourceName: 'Community Hand Pump', message: 'Contamination confirmed. Awaiting sanitization team.', status: WaterSourceStatus.Unsafe, timestamp: '2024-07-28 06:00 PM' },
    { id: 4, sourceName: 'River Pump Station', message: 'Potential contamination risk due to flooding upstream.', status: WaterSourceStatus.Warning, timestamp: '2024-07-27 10:00 AM' },
];

export const HEALTH_CENTERS: HealthCenter[] = [
    { id: 1, name: 'Guwahati Medical College', type: HealthCenterType.Hospital, lat: 26.1460, lng: 91.7853, contact: '1800-345-3755', hours: '24 Hours' },
    { id: 2, name: 'Dispur Urban Health Center', type: HealthCenterType.Clinic, lat: 26.1260, lng: 91.7820, contact: '0361-2233508', hours: '9 AM - 5 PM' },
    { id: 3, name: 'Dr. B. Das Clinic', type: HealthCenterType.Doctor, lat: 26.1510, lng: 91.7410, contact: '+91-9876543210', hours: '10 AM - 1 PM, 5 PM - 8 PM' },
    { id: 4, name: 'Apollo Pharmacy', type: HealthCenterType.Pharmacy, lat: 26.1400, lng: 91.7300, contact: '0361-2456789', hours: '8 AM - 10 PM' },
];

export const SYMPTOMS: Symptom[] = [
    { id: 'diarrhea', name: 'Diarrhea' },
    { id: 'vomiting', name: 'Vomiting' },
    { id: 'fever', name: 'Fever' },
    { id: 'stomach_cramps', name: 'Stomach Cramps' },
    { id: 'nausea', name: 'Nausea' },
    { id: 'headache', name: 'Headache' },
    { id: 'dehydration', name: 'Dehydration' },
    { id: 'fatigue', name: 'Fatigue' },
];

export const MOCK_SYMPTOM_REPORTS: SymptomReport[] = [
    { symptom: 'Diarrhea', count: 45, date: '2024-07-29'},
    { symptom: 'Vomiting', count: 25, date: '2024-07-29'},
    { symptom: 'Fever', count: 30, date: '2024-07-29'},
    { symptom: 'Stomach Cramps', count: 22, date: '2024-07-29'},
    { symptom: 'Nausea', count: 18, date: '2024-07-29'},
];

// For the line chart trend
export const MOCK_SYMPTOM_TREND_DATA = [
  { name: '7 days ago', Diarrhea: 12, Fever: 8, Vomiting: 5 },
  { name: '6 days ago', Diarrhea: 15, Fever: 10, Vomiting: 7 },
  { name: '5 days ago', Diarrhea: 13, Fever: 12, Vomiting: 6 },
  { name: '4 days ago', Diarrhea: 20, Fever: 15, Vomiting: 10 },
  { name: '3 days ago', Diarrhea: 28, Fever: 18, Vomiting: 15 },
  { name: '2 days ago', Diarrhea: 35, Fever: 22, Vomiting: 20 },
  { name: 'Yesterday', Diarrhea: 40, Fever: 25, Vomiting: 22 },
  { name: 'Today', Diarrhea: 45, Fever: 30, Vomiting: 25 },
];
